### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by theflimflam** [enesser/git-breakdown#6]
As a fellow on the internet, I want to use this script knowing under what terms I should be allowed to use it so that I can copy this into my bin directory and not think about it again.

At the moment, Eric J Nesser owns full copyright so copying this to my bin directory would be dubious.

**Comment by enesser** [comment]
You're free to do so. I just made the licensing explicit.

Thanks for the note!

**Comment by theflimflam** [comment]
You sir are a gentleman. Kudos on your awesome script!
